<?php
/*
 * Available variables:
 * 
 * $aOptions   - the plugin options
 * $aProducts  - the fetched product links
 * $aArguments - the user defined unit arguments such as image size and count etc.
 */

$_oOption = Externals_Option::getInstance();

echo '<?xml version="1.0" encoding="' . get_option( 'blog_charset' ) . '"?' . '>'; 

?>
<rss version="2.0"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:wfw="http://wellformedweb.org/CommentAPI/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:atom="http://www.w3.org/2005/Atom"
    xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
    xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
    <?php do_action( 'rss2_ns' ); ?>
>
<channel>
    <?php
        $sFeedTitle    = __( 'Feed Generated by Externals', 'externals' ) . ' - ' . get_bloginfo( 'name' );
        $_sExternalURL = bloginfo_rss( 'url' );
        if ( isset( $aArguments[ 'id' ] ) && $_oOption->get( 'external_preview', 'visible_to_guests' ) ) {
            $_sExternalURL = esc_url( get_permalink( $aArguments[ 'id' ] ) );
        }
    ?>
    <title><![CDATA[ <?php echo $sFeedTitle; ?>]]></title>
    <atom:link href="<?php self_link(); ?>" rel="self" type="application/rss+xml" />
    <link><?php echo $_sExternalURL; ?></link>
    <description><?php bloginfo_rss( 'description' ); ?></description>
    <lastBuildDate><?php echo mysql2date( 'D, d M Y H:i:s +0000', get_lastpostmodified( 'GMT' ), false ); ?></lastBuildDate>
    <language><?php bloginfo_rss( 'language' ); ?></language>
    <sy:updatePeriod><?php echo apply_filters( 'rss_update_period', 'hourly' ); ?></sy:updatePeriod>
    <sy:updateFrequency><?php echo apply_filters( 'rss_update_frequency', '1' ); ?></sy:updateFrequency>
    <?php 
        do_action( 'rss2_head' );         
        foreach ( $aItems as $_aItem ) : 
    ?>
    <item>
        <title><![CDATA[<?php echo $_aItem[ 'title' ]; ?>]]></title>
        <link><?php echo $_aItem[ 'permalink' ]; ?></link>
        <comments></comments>
        <pubDate><?php echo $_aItem[ 'date' ]; ?></pubDate>
        <dc:creator><![CDATA[<?php echo $_aItem[ 'author' ]; ?>]]></dc:creator>
        <category><![CDATA[]]></category>
        <guid isPermaLink="false"><?php echo $_aItem[ 'id' ]; ?></guid>
        <?php if ( $_oOption->get( 'feed', 'use_description_tag_for_rss_item_content' ) ) : ?>
        <description><![CDATA[<?php echo $_aItem[ 'content' ]; ?>]]></description>
        <?php else : ?>
        <description><![CDATA[<?php echo $_aItem[ 'description' ]; ?>]]></description>
        <content:encoded><![CDATA[<?php echo $_aItem[ 'content' ]; ?>]]></content:encoded>
        <?php endif; ?>
        <wfw:commentRss></wfw:commentRss>
        <slash:comments></slash:comments>
    <?php do_action( 'rss2_item' ); ?>
    </item>
    <?php endforeach; ?>
</channel>
</rss>